- name: Upgrade yum
  yum:
    name: "*"
    state: latest    
  become: yes

- name: installation of httpd
  yum:
    name: httpd
    state: latest    
  become: yes

- name: Ensure the httpd service is running
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
