- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: yes

- name: install the latest version of postgresql15
  dnf:
    name: postgresql15
    state: latest
  become: yes

- name: install the latest version of pip
  dnf:
    name: pip
    state: latest
  become: yes

- name: install the latest version of psycopg2
  pip:
    name: psycopg2-binary
    state: latest 

- name: Create abetest2 user
  postgresql_user:
    login_host: postgre.cisneq6hcd4s.ap-northeast-1.rds.amazonaws.com
    login_user: abetest
    login_password: abetest9801
    name: abetest2
    password: abetestpass
    db: postgredb
    priv: ALL
    role_attr_flags: CREATEDB,CREATEROLE,NOSUPERUSER