- name: Enable to install nginx
  shell: "amazon-linux-extras enable nginx1"        
  become: yes

- name: install nginx
  yum:
    name: nginx
    state: latest
  become: yes

- name: Ensure the nginx service is running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
