#postgresql14のイントール
- name: Enable to install postgresql14
  shell: "amazon-linux-extras install -y postgresql14"        
  become: yes

#yumのアップデート
- name: upgrade all packages
  yum:
    name: "*"
    state: latest
  become: yes

#pipのイントール
- name: install the latest version of pip
  yum:
    name: pip
    state: latest
  become: yes

#psycopg2のイントール
- name: install the latest version of psycopg2
  pip:
    name: psycopg2-binary
    state: latest 

#ユーザーの作成
- name: Create abetest2 user
  postgresql_user:
    login_host: postgre.cisneq6hcd4s.ap-northeast-1.rds.amazonaws.com
    login_user: abetest
    login_password: abetest9801
    name: abetest2
    password: abetestpass
    db: postgredb
    priv: ALL
    role_attr_flags: CREATEDB,CREATEROLE,NOSUPERUSER

#スキーマの作成
- name: Create a new schema with name acme in test database
  postgresql_schema:
    login_host: postgre.cisneq6hcd4s.ap-northeast-1.rds.amazonaws.com
    login_user: abetest2
    login_password: abetestpass
    db: postgredb
    name: abetest2