- name: creating_RDS
  rds:
    command: create
    instance_name: "{{ instance_name }}"
    db_engine: "{{ db_engine }}"
    size: 100
    instance_type: "{{ db_instance_type }}"
    username: "{{ username }}"
    password: "{{ password }}"
    db_name: "{{ db_name }}"
    region: ap-northeast-1
    subnet: "{{ subnet }}"
    parameter_group: "{{ parameter_group }}"
    option_group: "{{ option_group }}"
    vpc_security_groups: "{{ vpc_security_groups }}"
    publicly_accessible: no
    multi_zone: yes
    tags:
      Environment: "{{ tags_Environment }}"
      Application: cms